"""create users table

Revision ID: 0e523f6a4dc2
Revises:
Create Date: 2026-08-10 15:53:08.067755

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e523f6a4dc2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("service_id", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column(
            "rank",
            sa.Enum(
                "CONSTABLE",
                "HEAD_CONSTABLE",
                "ASSISTANT_SUB_INSPECTOR",
                "SUB_INSPECTOR",
                "CIRCLE_INSPECTOR",
                "DEPUTY_SUPERINTENDENT",
                "ADDITIONAL_SUPERINTENDENT",
                "SUPERINTENDENT",
                "DEPUTY_INSPECTOR_GENERAL",
                "INSPECTOR_GENERAL",
                "ADDITIONAL_DIRECTOR_GENERAL",
                "DIRECTOR_GENERAL",
                "ASSISTANT_COMMISSIONER",
                "DEPUTY_COMMISSIONER",
                "ADDITIONAL_COMMISSIONER",
                "COMMISSIONER_OF_POLICE",
                name="rank",
            ),
            nullable=False,
        ),
        sa.Column(
            "department",
            sa.Enum(
                "LAW_AND_ORDER",
                "TRAFFIC",
                "CRIME_BRANCH",
                "CID_CRIME_BRANCH",
                "SPECIAL_BRANCH",
                "SOG",
                "ATS",
                "CYBER_CRIME",
                "EOW",
                "ACB",
                "NARCOTICS",
                "AHTU",
                "WOMEN_SAFETY",
                "GRP",
                "RAC",
                "TELECOM",
                "FSL",
                "TRAINING",
                "VIGILANCE",
                "PHQ",
                name="department",
            ),
            nullable=False,
        ),
        sa.Column("date_of_joining", sa.Date(), nullable=False),
        sa.Column("mobile_number", sa.String(length=15), nullable=False),
        sa.Column("mail", sa.String(length=255), nullable=False),
        sa.Column(
            "blood_group",
            sa.Enum(
                "A_POSITIVE",
                "A_NEGATIVE",
                "B_POSITIVE",
                "B_NEGATIVE",
                "AB_POSITIVE",
                "AB_NEGATIVE",
                "O_POSITIVE",
                "O_NEGATIVE",
                name="bloodgroup",
            ),
            nullable=False,
        ),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=False),
        sa.Column("emergency_contact_number", sa.String(length=15), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mobile_number"),
    )
    op.create_index(op.f("ix_users_mail"), "users", ["mail"], unique=True)
    op.create_index(op.f("ix_users_service_id"), "users", ["service_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_service_id"), table_name="users")
    op.drop_index(op.f("ix_users_mail"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
